name: to_do_application
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logging: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  uuid: ^3.0.7
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.5
  path_provider: ^2.0.15
  sqflite: ^2.2.8+4
  dio: ^5.2.1+1
  http: ^0.13.6
  shared_preferences: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  enabled: true
