// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVZ7L5ktBn74vpb9YWmchGDDDvWOiAGLQ',
    appId: '1:430342625269:web:eb3e9e35cf3bb0666272bc',
    messagingSenderId: '430342625269',
    projectId: 'taskapp-a12a4',
    authDomain: 'taskapp-a12a4.firebaseapp.com',
    storageBucket: 'taskapp-a12a4.appspot.com',
    measurementId: 'G-L81RHVFZPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqjCHT-EWqaPGhcTPPF7MHPweK7Abd9J4',
    appId: '1:430342625269:android:2ac0701321d9fd2c6272bc',
    messagingSenderId: '430342625269',
    projectId: 'taskapp-a12a4',
    storageBucket: 'taskapp-a12a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI3e3IyVpEohnHQCbyJ_MfkAffNk-wBCQ',
    appId: '1:430342625269:ios:4c3c7ea36f6fa71c6272bc',
    messagingSenderId: '430342625269',
    projectId: 'taskapp-a12a4',
    storageBucket: 'taskapp-a12a4.appspot.com',
    iosClientId: '430342625269-t8tup5qhgeajtbgrfakij1q04lkocco9.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI3e3IyVpEohnHQCbyJ_MfkAffNk-wBCQ',
    appId: '1:430342625269:ios:4c3c7ea36f6fa71c6272bc',
    messagingSenderId: '430342625269',
    projectId: 'taskapp-a12a4',
    storageBucket: 'taskapp-a12a4.appspot.com',
    iosClientId: '430342625269-t8tup5qhgeajtbgrfakij1q04lkocco9.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApplication',
  );
}
